name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    uses: keving3ng/jonas-config/.github/workflows/deploy-service.yml@main
    with:
      service: vball-tracker
      host_port: 3000
      container_port: 3000
      run_extra_args: --env-file /mnt/user/appdata/vball-tracker/.env -v /mnt/user/appdata/vball-tracker:/data
      verdaccio_setup: true
    secrets: inherit
